# Generated by Django 5.0.1 on 2024-10-14 04:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_alter_event_options_alter_review_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["start_time"]},
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={},
        ),
    ]
